### PR TITLE
Adds better stream debugging for SendText methods

### LINKED ISSUE #86: [BUG]-Enabling Stream Debugging for GenericTcpClient should show text
**Describe the bug**
When stream debugging is enabled for the GenericTcpClient and the SendText method is used, the bytes for the text are printed to console instead of the string.

**Expected behavior**
The text should be printed to console instead of the bytes

### PR DESCRIPTION
**Pull request by alex-johnson**
Adds better debugging for SendText methods by printing text with non-ASCII and control characters replaced with hex representation.

Resolves #86

### CODE REVIEW

**Comment by alex-johnson** [comment]
This was tested for control characters but probably won't work well for non-ascii characters, I believe it will just print the first byte

**Comment by andrew-welker** [comment]
Can you fix this in all of the other classes that implement the interface and push to the same branch?

**Comment by alex-johnson** [comment]
@andrew-welker I did it for tcp client, udp server, and ssh client already. Are there more? Can't find anything else. There are some classes that print to the log that might be able to use it, but I just focused on the classes implementing IStreamDebugging which are those three.

**Comment by alex-johnson** [comment]
There are a lot of places in Essentials it can be used though

**Comment by andrew-welker** [comment]
Once the next version of Core is released, we'll add the same thing to the classes in Essentials that implement the interface. Thanks, and I'll get this approved and merged.

**Comment by ndorin** [comment]
> @andrew-welker I did it for tcp client, udp server, and ssh client already. Are there more? Can't find anything else. There are some classes that print to the log that might be able to use it, but I just focused on the classes implementing IStreamDebugging which are those three.

I think the other place is the ComPortController in Essentials where this is used?

**Review by ndorin — APPROVED** [review]

**Pull request merged**
